### ISSUE TITLE
Modèles : N-to-N

### ISSUE THREAD

**Issue by PonteIneptique** [Chartes-TNAH/prosopochartes#42]
Chères toutes,
Je note qu'il est un peu dommage de ne pas avoir plus de n-to-n, particulièrement sur les diplômes (agrégation + archiviste paléographe). Pareil pour les domaines. Un n-to-n serait tout de même apprécié.

**Comment by cabesse** [comment]
Monsieur, 

Effectivement il n'y a aucunes relations n-n dans notre modèle de donnée. (explications par e-mail suivent à ce propos).

C'est un peu dommage pour nous de voir votre pré-requis aujourd'hui après avoir passé une semaine très intensive sur le développement de notre application.

En l'état actuel, nous pourrions encore changer notre modèle sur une table (à savoir réécrire les données pour les 40 chercheurs qu'elle contient), modifier notre modèle de donnée, nos relationships, et toutes les fonctions de recherche qui y sont associées (c'est à dire au vu de notre construction de site l'intégralité de nos fonctions de recherche). Est-ce que vous accepteriez cette échelle de modification ? 

Il serait également très important pour nous, de ne pas devoir reprendre des choses depuis le début une nouvelle fois, aussi y-a-t-il d'autres points dont vous voudriez nous faire part avant que nous procédions aux changements ?

**Comment by PonteIneptique** [comment]
Chère madame,
Il ne s'agit pas d'un pré-requis explicite mais d'une recommendation, y
compris pour vous directement en terme de compétences.

**Comment by cabesse** [comment]
Nous allons modifier à priori la table occupation qui est la plus parlante au vue de nos données pour illustrer une relation n-n.
Les données présentes sur wikidata sont très lacunaires et nous avions complété manuellement la valeur 'archiviste paléographe' pour les diplômes.

**Comment by CamilleCarette** [comment]
Bonsoir Monsieur,

Cette issue ayant été résolue à travers les pull request référencées ci-dessus, au travers desquelles nous avons ajouté une relation n-n à notre base, je me permets de la clore. Merci pour vos remarques !
